# 00-secrets/netpulse-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: netpulse-secrets
type: Opaque
stringData:
  # IMPORTANT: Replace these placeholder passwords with secure values before deploying to production
  # You can set actual values using:
  # 1. Environment variables when applying with kubectl: kubectl apply -f <(envsubst < 00-secrets.yml)
  # 2. Direct edit: Replace these placeholders with actual secure passwords
  # 3. Use a secret management solution like HashiCorp Vault or Kubernetes External Secrets
  password: "redis-password-placeholder"  # Replace with a secure password
  api-key: "api-key-placeholder"  # Replace with a secure API key